springfox:
  documentation:
    swagger-ui:
      enabled: true

server:
  port: 8082
  servlet:
    context-path: /easyinsurance
    
spring:
  datasource:
    url: jdbc:h2:mem:plano;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: teste
  h2:
    console:
      enabled: true
      path: "/h2" 

